### ISSUE TITLE
Error while using detectObjectOnBinary 

### ISSUE THREAD

**Issue by sundhar010** [shaqian/flutter_tflite#114]
I am trying to use detectObjectOnBinary and getting an error. Am I doing something wrong here please let me know.

``` 
img.Image imageFile = img.decodeImage(File(widget.path).readAsBytesSync());
// var recognitions = await Tflite.detectObjectOnImage(path: widget.path); \\this works
var recognitions = await Tflite.detectObjectOnBinary(binary: imageToByteListFloat32(imageFile, imageFile.width, imageFile.height, 127.5, 127.5), asynch: true);
```
```
Uint8List imageToByteListFloat32(
      img.Image image, int width, int height, double mean, double std) {
    var convertedBytes = Float32List(1 * width * height * 3);
    var buffer = Float32List.view(convertedBytes.buffer);
    int pixelIndex = 0;
    for (var i = 0; i < height; i++) {
      for (var j = 0; j < width; j++) {
        var pixel = image.getPixel(j, i);
        buffer[pixelIndex++] = (img.getRed(pixel) - mean) / std;
        buffer[pixelIndex++] = (img.getGreen(pixel) - mean) / std;
        buffer[pixelIndex++] = (img.getBlue(pixel) - mean) / std;
      }
    }
    return convertedBytes.buffer.asUint8List();
  }
```

ERROR:

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(19433):        at android.os.AsyncTask$4.done(AsyncTask.java:399)
E/AndroidRuntime(19433):        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(19433):        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(19433):        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(19433):        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
E/AndroidRuntime(19433):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(19433):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(19433):        at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime(19433): Caused by: java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite buffer with 786432 bytes and a Java Buffer with 4147200 bytes.
E/AndroidRuntime(19433):        at org.tensorflow.lite.Tensor.throwIfShapeIsIncompatible(Tensor.java:332)
E/AndroidRuntime(19433):        at org.tensorflow.lite.Tensor.throwIfDataIsIncompatible(Tensor.java:305)
E/AndroidRuntime(19433):        at org.tensorflow.lite.Tensor.setTo(Tensor.java:123)
E/AndroidRuntime(19433):        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:150)
E/AndroidRuntime(19433):        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:311)
E/AndroidRuntime(19433):        at sq.flutter.tflite.TflitePlugin$RunSSDMobileNet.runTflite(TflitePlugin.java:622)
E/AndroidRuntime(19433):        at sq.flutter.tflite.TflitePlugin$TfliteTask.doInBackground(TflitePlugin.java:419)
E/AndroidRuntime(19433):        at sq.flutter.tflite.TflitePlugin$TfliteTask.doInBackground(TflitePlugin.java:393)
E/AndroidRuntime(19433):        at android.os.AsyncTask$3.call(AsyncTask.java:378)
E/AndroidRuntime(19433):        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(19433):        ... 4 more
W/System  (19433): A resource failed to call close.
W/System  (19433): A resource failed to call close.
I/Process (19433): Sending signal. PID: 19433 SIG: 9
Lost connection to device.
```

**Comment by sundhar010** [comment]
I tried `imageToByteListUint8` from the example even this did not work.
````
img.Image imageFile = img.decodeImage(File(widget.path).readAsBytesSync());
// var recognitions = await Tflite.detectObjectOnImage(path: widget.path);
var recognitions = await Tflite.detectObjectOnBinary(binary:imageToByteListUint8(imageFile, imageFile.width, imageFile.height));
```

```
Uint8List imageToByteListUint8(img.Image image, int width, int height) {
    var convertedBytes = Uint8List(1 * width * height * 3);
    var buffer = Uint8List.view(convertedBytes.buffer);
    int pixelIndex = 0;
    for (var i = 0; i < height; i++) {
      for (var j = 0; j < width; j++) {
        var pixel = image.getPixel(j, i);
        buffer[pixelIndex++] = img.getRed(pixel);
        buffer[pixelIndex++] = img.getGreen(pixel);
        buffer[pixelIndex++] = img.getBlue(pixel);
      }
    }
    return convertedBytes.buffer.asUint8List();
  }
```

Error:
```
 java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(22287):        at android.os.AsyncTask$4.done(AsyncTask.java:399)
E/AndroidRuntime(22287):        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(22287):        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(22287):        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(22287):        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
E/AndroidRuntime(22287):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(22287):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(22287):        at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime(22287): Caused by: java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite buffer with 786432 bytes and a Java Buffer with 1036800 bytes.
E/AndroidRuntime(22287):        at org.tensorflow.lite.Tensor.throwIfShapeIsIncompatible(Tensor.java:332)
E/AndroidRuntime(22287):        at org.tensorflow.lite.Tensor.throwIfDataIsIncompatible(Tensor.java:305)
E/AndroidRuntime(22287):        at org.tensorflow.lite.Tensor.setTo(Tensor.java:123)
E/AndroidRuntime(22287):        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:150)
E/AndroidRuntime(22287):        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:311)
E/AndroidRuntime(22287):        at sq.flutter.tflite.TflitePlugin$RunSSDMobileNet.runTflite(TflitePlugin.java:622)
E/AndroidRuntime(22287):        at sq.flutter.tflite.TflitePlugin$TfliteTask.doInBackground(TflitePlugin.java:419)
E/AndroidRuntime(22287):        at sq.flutter.tflite.TflitePlugin$TfliteTask.doInBackground(TflitePlugin.java:393)
E/AndroidRuntime(22287):        at android.os.AsyncTask$3.call(AsyncTask.java:378)
E/AndroidRuntime(22287):        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(22287):        ... 4 more
W/System  (22287): A resource failed to call close.
W/System  (22287): A resource failed to call close.
I/Process (22287): Sending signal. PID: 22287 SIG: 9
Lost connection to device.
```

**Comment by sundhar010** [comment]
I found out what the issue is. I have to resize the image to `normalized_input_image_tensor` after doing that this function worked.

Thanks

**Comment by GokulDas027** [comment]
@sundhar010  How did you did that?
> resizing the image to "normalized_input_image_tensor"
I am having the same error, what is normalized_input_image_tensor?
