### ISSUE TITLE
loadModel Error if it is called in an isolate

### ISSUE THREAD

**Issue by sundhar010** [shaqian/flutter_tflite#115]
I have a set of images and I want to run `detectObjectOnBinary` parallely. but I am getting this error if I try to load the model in an isolate.

```
ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
E/flutter (10626): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during 
plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
E/flutter (10626): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
E/flutter (10626): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
E/flutter (10626): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
E/flutter (10626): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
E/flutter (10626): #3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
E/flutter (10626): #4      Tflite.loadModel (package:tflite/tflite.dart:14:27)
E/flutter (10626): #5      detectCharsFromBlock (package:michelin/display.dart:236:29)
E/flutter (10626): #6      _Processor.process (package:pmap/pmap.dart:17:66)
E/flutter (10626): #7      _process (package:pmap/pmap.dart:30:17)
E/flutter (10626): <asynchronous suspension>
E/flutter (10626): #8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:310:17)
E/flutter (10626): #9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by VadPinchuk** [comment]
The issue is in that, tflite is not registered in isolate. So you would better dig into "how isolates works" rather than blame.
