### ISSUE TITLE
Issue in detectObjectOnImage

### ISSUE THREAD

**Issue by pablo3x6** [shaqian/flutter_tflite#152]
```
D/AndroidRuntime( 6187): Shutting down VM
E/AndroidRuntime( 6187): FATAL EXCEPTION: main
E/AndroidRuntime( 6187): Process: com.example.pptuj_cam, PID: 6187
E/AndroidRuntime( 6187): java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 1
E/AndroidRuntime( 6187): 	at java.util.Vector.get(Vector.java:748)
E/AndroidRuntime( 6187): 	at sq.flutter.tflite.TflitePlugin$RunSSDMobileNet.onRunTfliteDone(TflitePlugin.java:663)
E/AndroidRuntime( 6187): 	at sq.flutter.tflite.TflitePlugin$TfliteTask.onPostExecute(TflitePlugin.java:454)
E/AndroidRuntime( 6187): 	at sq.flutter.tflite.TflitePlugin$TfliteTask.onPostExecute(TflitePlugin.java:422)
E/AndroidRuntime( 6187): 	at android.os.AsyncTask.finish(AsyncTask.java:755)
E/AndroidRuntime( 6187): 	at android.os.AsyncTask.access$900(AsyncTask.java:192)
E/AndroidRuntime( 6187): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
E/AndroidRuntime( 6187): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime( 6187): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 6187): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 6187): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6187): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 6187): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/Process ( 6187): Sending signal. PID: 6187 SIG: 9
```

Would anyone know what led to this error?
It happens when i try to detect something in an image.

Code:
```
class _AiPageState extends State<AiPage> {
  _loadModel() async {
    String res = await Tflite.loadModel(
        model: "assets/model.tflite",
        labels: "assets/labels.txt",
        numThreads: 1, // defaults to 1
        isAsset:
            true, // defaults to true, set to false to load resources outside assets
        useGpuDelegate:
            false // defaults to false, set to true to use GPU delegate
        );
  }

  _releaseResource() async {
    await Tflite.close();
  }

  _runOnImage() async {
    var recognitions = await Tflite.detectObjectOnImage(
        path: widget.directory, // required
        model: "SSDMobileNet",
        imageMean: 127.5,
        imageStd: 127.5,
        threshold: 0.4, // defaults to 0.1
        numResultsPerClass: 1, // defaults to 5
        asynch: true // defaults to true
        );
    
    print(recognitions);
    _releaseResource();
    return recognitions;
  }

  List text = [];

  @override
  Widget build(BuildContext context) {
    _loadModel();
    return Scaffold(
      body: SafeArea(
        child: StreamBuilder<Object>(
            stream: _runOnImage().asStream(),
            builder: (context, snapshot) {
              if (snapshot == null || snapshot.data == null) {
                return Text('none found');
              }

              return Text(
                snapshot.data.toString(),
                style: TextStyle(
                  fontSize: 25,
                ),
              );
            }),
      ),
    );
  }
}
```

**Comment by shaqian** [comment]
The exception is thrown near [here](https://github.com/shaqian/flutter_tflite/blob/master/android/src/main/java/sq/flutter/tflite/TflitePlugin.java#L663). Can you set a breakpoint [here](https://github.com/shaqian/flutter_tflite/blob/master/android/src/main/java/sq/flutter/tflite/TflitePlugin.java#L654) and debug which array is giving "Array index out of range: 1"?

Thanks,
Qian
