### ISSUE TITLE
NullPointerException in Android Release mode

### ISSUE THREAD

**Issue by VadPinchuk** [shaqian/flutter_tflite#157]
PlatformException(Failed to run model, Attempt to invoke virtual method 'org.tensorflow.lite.Tensor org.tensorflow.lite.Interpreter.getInputTensor(int)' on a null object reference, java.lang.NullPointerException: Attempt to invoke virtual method 'org.tensorflow.lite.Tensor org.tensorflow.lite.Interpreter.getInputTensor(int)' on a null object reference
I/flutter (25062):      at sq.flutter.tflite.TflitePlugin.feedInputTensor(TflitePlugin.java:326)
I/flutter (25062):      at sq.flutter.tflite.TflitePlugin.feedInputTensorImage(TflitePlugin.java:371)
I/flutter (25062):      at sq.flutter.tflite.TflitePlugin.detectObjectOnImage(TflitePlugin.java:565)
I/flutter (25062):      at sq.flutter.tflite.TflitePlugin.onMethodCall(TflitePlugin.java:120)
I/flutter (25062):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
I/flutter (25062):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
I/flutter (25062):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
I/flutter (25062):      at android.os.MessageQueue.nativePollOnce(Native Method)
I/flutter (25062):      at android.os.MessageQu

**Comment by carnevalli** [comment]
Please, check if you've added these lines inside `android` block in `android/app/build.gradle`
```
    aaptOptions {
        noCompress 'tflite'
        noCompress 'lite'
    }
```

**Comment by crisfox** [comment]
Find the solution? The same thing happens to me in the release compilation, only in production

**Comment by VadymPinchuk** [comment]
> Please, check if you've added these lines inside `android` block in `android/app/build.gradle`
> 
> ```
>     aaptOptions {
>         noCompress 'tflite'
>         noCompress 'lite'
>     }
> ```

Yes this was added

**Comment by Sk-Mattes** [comment]
Anyone found the solution? 

`
aaptOptions {
        noCompress 'tflite'
        noCompress 'lite'
    }
`
This doesnt seem to fix the Problem at least for me.

Kind regards!
