### ISSUE TITLE
Crash after detectObjectOnImage

### ISSUE THREAD

**Issue by pablo3x6** [shaqian/flutter_tflite#160]
After tflite finds the object it's looking for, it just crashes.

Here is the log:
```
D/AndroidRuntime( 4731): Shutting down VM
E/AndroidRuntime( 4731): FATAL EXCEPTION: main
E/AndroidRuntime( 4731): Process: com.example.pptuj_cam, PID: 4731
E/AndroidRuntime( 4731): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.Vector.get(int)' on a null object reference
E/AndroidRuntime( 4731): 	at sq.flutter.tflite.TflitePlugin$RunSSDMobileNet.onRunTfliteDone(TflitePlugin.java:663)
E/AndroidRuntime( 4731): 	at sq.flutter.tflite.TflitePlugin$TfliteTask.onPostExecute(TflitePlugin.java:454)
E/AndroidRuntime( 4731): 	at sq.flutter.tflite.TflitePlugin$TfliteTask.onPostExecute(TflitePlugin.java:422)
E/AndroidRuntime( 4731): 	at android.os.AsyncTask.finish(AsyncTask.java:755)
E/AndroidRuntime( 4731): 	at android.os.AsyncTask.access$900(AsyncTask.java:192)
E/AndroidRuntime( 4731): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
E/AndroidRuntime( 4731): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime( 4731): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 4731): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 4731): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4731): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 4731): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/Process ( 4731): Sending signal. PID: 4731 SIG: 9
Lost connection to device.
Exited (sigterm)
```

Would anyone know what the issue seems to be from this error?

**Comment by shaqian** [comment]
The exception is thrown from onRunTfliteDone. Can you debug if `labels` is null?
https://github.com/shaqian/flutter_tflite/blob/master/android/src/main/java/sq/flutter/tflite/TflitePlugin.java#L683

Thanks,
Qian

**Comment by pablo3x6** [comment]
Im sorry for late reply. Label file was null indeed.
