### ISSUE TITLE
Crash on Android 6.0

### ISSUE THREAD

**Issue by ashish-andev** [shaqian/flutter_tflite#165]
Everytime app crashes when I try to load model using 
```
Tflite.loadModel(
        model: "xxxx",
        labels: "xxxx",
      );
```

**Crash Log:**

```
I/RequestThread-1( 9273): configureOutputs - set take picture size to 1920x1080
E/HAL     ( 9273): Dawei load: module=/system/lib64/hw/gralloc.msm8937.so
I/CameraDeviceState( 9273): Legacy camera service transitioning to state IDLE
E/flutter ( 9273): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.NoSuchMethodError: No virtual method getOrDefault(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Ljava/util/HashMap; or its super classes (declaration of 'java.util.HashMap' appears in /system/framework/core-libart.jar)
E/flutter ( 9273): 	at sq.flutter.tflite.a.a(SourceFile:221)
E/flutter ( 9273): 	at sq.flutter.tflite.a.a(SourceFile:95)
E/flutter ( 9273): 	at io.flutter.plugin.common.j$a.a(SourceFile:233)
E/flutter ( 9273): 	at io.flutter.embedding.engine.b.b.a(SourceFile:85)
E/flutter ( 9273): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(SourceFile:692)
E/flutter ( 9273): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 9273): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/flutter ( 9273): 	at android.os.Looper.loop(Looper.java:138)
E/flutter ( 9273): 	at android.app.ActivityThread.main(ActivityThread.java:5523)
E/flutter ( 9273): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 9273): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
E/flutter ( 9273): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
E/flutter ( 9273): 
F/flutter ( 9273): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(942)] Check failed: CheckException(env). 
```

**Comment by maelfosso** [comment]
@ashish-andev dis you solve it, please?

I have thé same issue

**Comment by ashish-andev** [comment]
> @ashish-andev dis you solve it, please?
> 
> I have thé same issue

No @maelfosso I have just disabled the feature for Android 6.0 and below, as I have very few users for those Android versions

**Comment by maelfosso** [comment]
@ashish-andev thank you
I think I will do like you

**Comment by Dangtrungphu** [comment]
I have the same issue

**Comment by Dangtrungphu** [comment]
I have found the cause of problem. Method getOrDefault() not use api smaller 24. Because i change code simple

From: 
`boolean useGpuDelegate = (boolean) args.getOrDefault("useGpuDelegate", false);`

To:
`    boolean useGpuDelegate = true;`
    `String tam = args.get("useGpuDelegate").toString();`
 `   if (tam == "null" || tam == "false") {`
    `  useGpuDelegate = false;`
   ` } else{`
     ` useGpuDelegate = true;`
`    }`

Hope this is true for everyone.
