### ISSUE TITLE
Crashes when use custom pose estimation model 'MoveNet'

### ISSUE THREAD

**Issue by SamedHrmn** [shaqian/flutter_tflite#214]
Hi , I was trying to use MoveNet tflite model with this package. Code like this,:

`detectPose() {
    controller.startImageStream((CameraImage img) {
      if (!isDetecting) {
        isDetecting = true;

        Tflite.runModelOnFrame(
          bytesList: img.planes.map((plane) {
            return plane.bytes;
          }).toList(),
          imageHeight: img.height,
          imageWidth: img.width,
        );
      }
    });
  }`

and app crashes with this console log,

I/CameraManagerGlobal(27824): Connecting to camera service
W/.movenet_sample(27824): type=1400 audit(0.0:9336): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=5328 scontext=u:r:untrusted_app:s0:c154,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
E/libc    (27824): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (27824): Access denied finding property "vendor.camera.aux.packagelist2"
E/libc    (27824): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (27824): Access denied finding property "vendor.camera.aux.packagelist2"
E/libc    (27824): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (27824): Access denied finding property "vendor.camera.aux.packagelist2"
W/CameraManagerGlobal(27824): [soar.cts] ignore the status update of camera: 2
E/libc    (27824): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (27824): Access denied finding property "vendor.camera.aux.packagelist2"
W/CameraManagerGlobal(27824): [soar.cts] ignore the status update of camera: 3
E/libc    (27824): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (27824): Access denied finding property "vendor.camera.aux.packagelist2"
E/libc    (27824): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (27824): Access denied finding property "vendor.camera.aux.packagelist2"
E/libc    (27824): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (27824): Access denied finding property "vendor.camera.aux.packagelist2"
W/CameraManagerGlobal(27824): ignore the torch status update of camera: 2
E/libc    (27824): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (27824): Access denied finding property "vendor.camera.aux.packagelist2"
W/CameraManagerGlobal(27824): ignore the torch status update of camera: 3
I/tflite  (27824): Initialized TensorFlow Lite runtime.
I/flutter (27824): Model: lite-model_movenet_singlepose_lightning_3.tflite
I/flutter (27824): Model Load State : success
I/Camera  (27824): [FPS Range Available] is:[15, 15]
I/Camera  (27824): [FPS Range Available] is:[20, 20]
I/Camera  (27824): [FPS Range Available] is:[24, 24]
I/Camera  (27824): [FPS Range Available] is:[7, 25]
I/Camera  (27824): [FPS Range Available] is:[25, 25]
I/Camera  (27824): [FPS Range Available] is:[7, 30]
I/Camera  (27824): [FPS Range Available] is:[30, 30]
I/Camera  (27824): [FPS Range] is:[7, 30]
W/Camera  (27824): The selected imageFormatGroup is not supported by Android. Defaulting to yuv420
E/libc    (27824): Access denied finding property "persist.vendor.camera.privapp.list"
W/.movenet_sample(27824): type=1400 audit(0.0:9352): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=5328 scontext=u:r:untrusted_app:s0:c154,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
I/CameraManager(27824): Using legacy camera HAL.
E/libc    (27824): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (27824): Access denied finding property "vendor.camera.aux.packagelist2"
E/libc    (27824): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (27824): Access denied finding property "vendor.camera.aux.packagelist2"
W/Binder:27824_1(27824): type=1400 audit(0.0:9353): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=5328 scontext=u:r:untrusted_app:s0:c154,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
E/libc    (27824): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (27824): Access denied finding property "vendor.camera.aux.packagelist2"
I/CameraDeviceState(27824): Legacy camera service transitioning to state CONFIGURING
I/RequestThread-0(27824): Configure outputs: 2 surfaces configured.
D/Camera  (27824): app passed NULL surface
I/RequestThread-0(27824): configureOutputs - set take picture size to 1280x720
E/libc    (27824): Access denied finding property "persist.camera.legacy_perf"
I/CameraDeviceState(27824): Legacy camera service transitioning to state IDLE
I/RequestQueue(27824): Repeating capture request set.
W/LegacyRequestMapper(27824): convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
I/RequestQueue(27824): Repeating capture request cancelled.
I/CameraDeviceState(27824): Legacy camera service transitioning to state CAPTURING
I/CameraDeviceState(27824): Legacy camera service transitioning to state IDLE
I/CameraDeviceState(27824): Legacy camera service transitioning to state CONFIGURING
I/RequestThread-0(27824): Configure outputs: 2 surfaces configured.
D/Camera  (27824): app passed NULL surface
E/libc    (27824): Access denied finding property "persist.camera.legacy_perf"
I/CameraDeviceState(27824): Legacy camera service transitioning to state IDLE
I/RequestQueue(27824): Repeating capture request set.
W/LegacyRequestMapper(27824): convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
I/CameraDeviceState(27824): Legacy camera service transitioning to state CAPTURING
W/System  (27824): A resource failed to call release.
2
W/System  (27824): A resource failed to call close.
D/RenderScript HIDL Adaptation(27824): IRenderScriptDevice::getService()
D/vndksupport(27824): Loading /vendor/lib64/hw/android.hardware.renderscript@1.0-impl.so from current namespace instead of sphal namespace.
D/RenderScript HIDL Adaptation(27824): IRenderScriptDevice::getService() returned 0x735ff0b700
D/RenderScript HIDL Adaptation(27824): HIDL successfully loaded.
V/RenderScript(27824): Successfully loaded runtime: libRSDriver_adreno.so
D/        (27824): Successfully queried cache dir: /data/user_de/0/com.example.movenet_sample/code_cache
D/RenderScript(27824): Setting cache dir: /data/user_de/0/com.example.movenet_sample/code_cache
W/System  (27824): A resource failed to call destroy.
I/chatty  (27824): uid=10410(com.example.movenet_sample) FinalizerDaemon identical 1 line
W/System  (27824): A resource failed to call destroy.
E/AndroidRuntime(27824): FATAL EXCEPTION: AsyncTask #2
E/AndroidRuntime(27824): Process: com.example.movenet_sample, PID: 27824
E/AndroidRuntime(27824): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(27824): 	at android.os.AsyncTask$3.done(AsyncTask.java:354)
E/AndroidRuntime(27824): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(27824): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(27824): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(27824): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
E/AndroidRuntime(27824): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(27824): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(27824): 	at java.lang.Thread.run(Thread.java:764)
E/AndroidRuntime(27824): Caused by: java.lang.IllegalArgumentException: Null outputs are allowed only if the Tensor is bound to a buffer handle.
E/AndroidRuntime(27824): 	at org.tensorflow.lite.Tensor.copyTo(Tensor.java:251)
E/AndroidRuntime(27824): 	at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:216)
E/AndroidRuntime(27824): 	at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:374)
E/AndroidRuntime(27824): 	at org.tensorflow.lite.Interpreter.run(Interpreter.java:332)
E/AndroidRuntime(27824): 	at sq.flutter.tflite.TflitePlugin$RunModelOnFrame.runTflite(TflitePlugin.java:565)
E/AndroidRuntime(27824): 	at sq.flutter.tflite.TflitePlugin$TfliteTask.doInBackground(TflitePlugin.java:471)
E/AndroidRuntime(27824): 	at sq.flutter.tflite.TflitePlugin$TfliteTask.doInBackground(TflitePlugin.java:445)
E/AndroidRuntime(27824): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
E/AndroidRuntime(27824): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(27824): 	... 4 more
I/Process (27824): Sending signal. PID: 27824 SIG: 9
Lost connection to device.
Exited (sigterm)

**Comment by JonasJW** [comment]
Any updates?
