### ISSUE TITLE
Migrate to support Android V2 embedding

### ISSUE THREAD

**Issue by erikbg7** [shaqian/flutter_tflite#225]
Migration guideline: https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

Current issues: https://github.com/shaqian/flutter_tflite/issues/220 https://github.com/shaqian/flutter_tflite/issues/224

**Comment by ss-zheng** [comment]
When will you support android v2 embedding?

**Comment by kartikeyaa-k** [comment]
Yes any update on android v2 embedding?

**Comment by DennisKragekjaer** [comment]
Same question here

**Comment by Puspharaj** [comment]
```
 package io.flutter.plugins.firebasecoreexample;

 import io.flutter.embedding.android.FlutterActivity;
 import io.flutter.embedding.engine.FlutterEngine;
 import io.flutter.plugins.firebase.core.FirebaseCorePlugin;

 public class MainActivity extends FlutterActivity {
   // You can keep this empty class or remove it. Plugins on the new embedding
   // now automatically registers plugins.
 }

```

**Comment by rafay-tariq** [comment]
can you tell me where to add these lines ? 
@Puspharaj

**Comment by Puspharaj** [comment]
> can you tell me where to add these lines ? @Puspharaj

I just pointed out that, It can be implemented in that way as suggested by the flutter team. However the whole plugin needs to be restructured to meet current guidelines of the flutter.
I have just forked. I need to restructure the plugin. It takes time. 

But only v2 embedding error thrown out, App can be build with those errors no issues you can try it out.

**Comment by rafay-tariq** [comment]
but it is crashing the application when I am using imagesegmentation.

**Comment by Puspharaj** [comment]
Pull example and run in your local machine to see if it's crash or not. 

Post your error log.

**Comment by rafay-tariq** [comment]
when i run this project it works but when i run image segmentation on flutter version 2.5 version (above null safety) it crash the whole project and kill the app

` A resource failed to call close. 
The Flutter DevTools debugger and profiler on sdk gphone arm64 is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:61030/_lmORiwaicE=/
E/libc    ( 6668): Access denied finding property "ro.hardware.chipname"
V/time    ( 6668): Inference took 156
D/AndroidRuntime( 6668): Shutting down VM
E/AndroidRuntime( 6668): FATAL EXCEPTION: main
E/AndroidRuntime( 6668): Process: com.tfliteflutteryolokshitizninja.flutter_tflite, PID: 6668
E/AndroidRuntime( 6668): java.lang.IndexOutOfBoundsException: Index: 15, Size: 1
E/AndroidRuntime( 6668):        at java.util.ArrayList.get(ArrayList.java:437)
E/AndroidRuntime( 6668):        at sq.flutter.tflite.TflitePlugin.fetchArgmax(TflitePlugin.java:1153)
E/AndroidRuntime( 6668):        at sq.flutter.tflite.TflitePlugin$RunSegmentationOnImage.onRunTfliteDone(TflitePlugin.java:1035)
E/AndroidRuntime( 6668):        at sq.flutter.tflite.TflitePlugin$TfliteTask.onPostExecute(TflitePlugin.java:477)
E/AndroidRuntime( 6668):        at sq.flutter.tflite.TflitePlugin$TfliteTask.onPostExecute(TflitePlugin.java:445)
E/AndroidRuntime( 6668):        at android.os.AsyncTask.finish(AsyncTask.java:771)
E/AndroidRuntime( 6668):        at android.os.AsyncTask.access$900(AsyncTask.java:199)
E/AndroidRuntime( 6668):        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
E/AndroidRuntime( 6668):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 6668):        at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 6668):        at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 6668):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6668):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 6668):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process ( 6668): Sending signal. PID: 6668 SIG: 9
Lost connection to device.`

**Comment by guccisekspir** [comment]
Any updates ?

**Comment by nawzhin95** [comment]
any updates ?

**Comment by zhengbomo** [comment]
https://github.com/shaqian/flutter_tflite/pull/230

**Comment by Omer-Rahmany** [comment]
Using @zhengbomo solution by changing the podspec file:
  tflite:
    git:
      url: git@github.com:zhengbomo/flutter_tflite.git
      
   - Worked only on the android emulator for me

**Comment by NavidHosseini** [comment]
Hello, you can use my repo

tflite_maven:
  git:
    url:  https://github.com/NavidHosseini/tflite.git
    ref: master

Its is work fine for now

example :  https://github.com/NavidHosseini/tflite/blob/master/example/example%20real%20time.rar

**Comment by Puspharaj** [comment]
nice

**Comment by JohnKisisri** [comment]
@NavidHosseini Is there a guide on how to update the plugin? It says your tflite is not supported for v2

**Comment by Tiran-Jayasekara** [comment]
tflite is working for flutter? still not?
