### ISSUE TITLE
Image Classification: Run on image stream not working

### ISSUE THREAD

**Issue by damiafuentes** [shaqian/flutter_tflite#28]
I am trying to do Image Classification for every frame. I have this code:
```
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:camera/camera.dart';
import 'package:tflite/tflite.dart';

List<CameraDescription> cameras;

Future<void> main() async {
  cameras = await availableCameras();
  runApp(CameraApp());
}

class CameraApp extends StatefulWidget {
  @override
  _CameraAppState createState() => _CameraAppState();
}

class _CameraAppState extends State<CameraApp> {
  CameraController controller;
  bool isDetecting = false;
  bool tfLoaded = false;

  @override
  void initState() {
    super.initState();
    loadTensorFlow();
    loadCamera();
  }

  void loadCamera(){
    if (cameras == null || cameras.length < 1) {
      print('No camera is found');
    } else {
      controller = CameraController(cameras[0], ResolutionPreset.high);
      controller.initialize().then((_) {
        if (!mounted) return;
        setState(() {});

        controller.startImageStream((CameraImage img) {
          if (isDetecting) return;
          if (!tfLoaded) return;
          isDetecting = true;
          try {
            int startTime = new DateTime.now().millisecondsSinceEpoch;
            print("Camera format ${img.format.group}");
            Tflite.runModelOnFrame(
                bytesList: img.planes.map((plane) {return plane.bytes;}).toList(),
                imageHeight: img.height,
                imageWidth: img.width,
                imageMean: 127.5,   // defaults to 127.5
                imageStd: 127.5,    // defaults to 127.5
                rotation: 90,       // defaults to 90, Android only
                numResults: 2,      // defaults to 5
                threshold: 0.1,     // defaults to 0.1
                asynch: true        // defaults to true
            ).then((recognitions) {
              print("Recognitions: $recognitions");
              print("Detection took ${new DateTime.now().millisecondsSinceEpoch - startTime}");
              isDetecting = false;
            });
          } catch (e) {
            print(e);
            isDetecting = false;
          }
        });
      });
    }
  }

  @override
  void dispose() {
    controller?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!controller.value.isInitialized) {
      return Container();
    }
    return AspectRatio(
        aspectRatio:
        controller.value.aspectRatio,
        child: CameraPreview(controller));
  }

  // Load model and labels
  void loadTensorFlow() async{
    String res = await Tflite.loadModel(
        model: "assets/tf/mobilenet_v1_1.0_224_quant.tflite",
        labels: "assets/tf/labels_mobilenet_quant_v1_224.txt",
        numThreads: 1,
    );
    setState(() {
      if(res != null) {
        tfLoaded = true;
      }
    });
  }
}
```

And I am having the following error:
```
E/AndroidRuntime( 9556): FATAL EXCEPTION: AsyncTask #2
E/AndroidRuntime( 9556): Process: com.myapp.myapp, PID: 9556
E/AndroidRuntime( 9556): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime( 9556): 	at android.os.AsyncTask$3.done(AsyncTask.java:353)
E/AndroidRuntime( 9556): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime( 9556): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime( 9556): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime( 9556): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
E/AndroidRuntime( 9556): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/AndroidRuntime( 9556): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/AndroidRuntime( 9556): 	at java.lang.Thread.run(Thread.java:764)
E/AndroidRuntime( 9556): Caused by: java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite tensor with type UINT8 and a Java object of type [[F (which is compatible with the TensorFlowLite type FLOAT32).
E/AndroidRuntime( 9556): 	at org.tensorflow.lite.Tensor.throwExceptionIfTypeIsIncompatible(Tensor.java:233)
E/AndroidRuntime( 9556): 	at org.tensorflow.lite.Tensor.copyTo(Tensor.java:116)
E/AndroidRuntime( 9556): 	at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:157)
E/AndroidRuntime( 9556): 	at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:250)
E/AndroidRuntime( 9556): 	at org.tensorflow.lite.Interpreter.run(Interpreter.java:228)
E/AndroidRuntime( 9556): 	at sq.flutter.tflite.TflitePlugin$RunModelOnFrame.runTflite(TflitePlugin.java:478)
E/AndroidRuntime( 9556): 	at sq.flutter.tflite.TflitePlugin$TfliteTask.doInBackground(TflitePlugin.java:389)
E/AndroidRuntime( 9556): 	at sq.flutter.tflite.TflitePlugin$TfliteTask.doInBackground(TflitePlugin.java:363)
E/AndroidRuntime( 9556): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
E/AndroidRuntime( 9556): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime( 9556): 	... 4 more
```

I am doing what it is said in the README.md --> Image Classification --> Run on image stream (video frame). I have tried with camera version ^0.4.3+2 and 0.4.0 (I suppose you mean that one when saying 4.0.0 in the README.md). I have also checked that my android phone is in YUV_420 and it is.

**Comment by shaqian** [comment]
Hi,

Unfortunately I couldn't reproduce the issue on my end. I'm using camera 0.4.0 and tflite 1.0.3. Can you try using the model file mobilenet_v1_1.0_224.tflite and mobilenet_v1_1.0_224.txt in this repo?

If you debug CameraImage img, does it contain 3 planes and the format set to "ImageFormatGroup.yuv420"?

Thanks,
Qian

**Comment by damiafuentes** [comment]
Hey,

Using your model file, model labels, camera: ^0.4.3+2 and tflite: ^1.0.3 worked for me. But is not working when using the quant models.

Thank you,
Damià

**Comment by jithin-pal** [comment]
I have built a custom ML model, when it comes to prediction it is crashing the application. What is the error? When i use the mobilenet downloaded from internet works fine. How do i fix this?

**Comment by chaoyifei** [comment]
> Hey,
> 
> Using your model file, model labels, camera: ^0.4.3+2 and tflite: ^1.0.3 worked for me. But is not working when using the quant models.
> 
> Thank you, Damià
Haver you  solve this pr when using the quant models
