### ISSUE TITLE
Missing Plugin Exeption

### ISSUE THREAD

**Issue by GiannosP14** [shaqian/flutter_tflite#297]
Hi , I get this issue and sadly i have no idea how to solve it. Thanks in advance.

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method loadModel on channel tflite)
E/flutter (25262): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter (25262): <asynchronous suspension>
E/flutter (25262): #1      Tflite.loadModel (package:tflite/tflite.dart:15:12)
E/flutter (25262): <asynchronous suspension>
E/flutter (25262): #2      _ObjectRecognitionHomePageState.loadModel (package:in_sight/core/modules/object_recognition/object_recognition_home_page.dart:99:5)
E/flutter (25262): <asynchronous suspension>
E/flutter (25262):

**Comment by ardeshir-33033** [comment]
@GiannosP14  did you find any fix for this?

**Comment by GiannosP14** [comment]
@ardeshir-33033 Hi, sadly no. I think I ended up using another similar package...

**Comment by sumn2u** [comment]
I made some updates and created my own version, which I applied to my [app](https://www.dwaste.live/).

You can find the updated version [here](https://github.com/sumn2u/flutter_tflite).
