### ISSUE TITLE
Too many positional arguments: 1 allowed, but 3 found

### ISSUE THREAD

**Issue by ajinkya933** [shaqian/flutter_tflite#33]
I am getting this error 

```                                                  
Compiler message:                                                       
lib/main.dart:167:44: Error: Too many positional arguments: 1 allowed, but 3 found.
Try removing the extra positional arguments.                            
    img.Image resizedImage = img.copyResize(oriImage, 224, 224);        
                                           ^                            
file:///Users/ajinkyabobade/development/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.1.2/lib/src/transform/copy_resize.dart:14:7: Context: Found this candidate, but the arguments don't match.
Image copyResize(Image src, {int width, int height,                     
      ^^^^^^^^^^                                                        
Compiler failed on /Users/ajinkyabobade/Documents/flutter_tflite/example/lib/main.dart
```

How to resolve it ?

**Comment by shaqian** [comment]
Hi,

Looks like `image` library changed `copySize` API in recently.
https://github.com/brendan-duncan/image/commit/ab86ca9f4180fea9b375c07f88a20d4c05726591#diff-77b497f4b86eb2017b1c91d05506d0c9

You can either fix `image` version to 2.0.5 
https://github.com/shaqian/flutter_tflite/blob/master/example/pubspec.yaml#L29
or change the code to
`img.Image resizedImage = img.copyResize(oriImage, width: 224, height: 224);`

**Comment by ajinkya933** [comment]
@shaqian Your solution removed above error, I am getting new errors:

The first one is as follows:

<img width="803" alt="Screenshot 2019-05-28 at 2 18 25 PM" src="https://user-images.githubusercontent.com/17012391/58464526-76fbe880-8153-11e9-9e70-8524e41bf05b.png">

I removed above error by replacing 'compile' by 'implementation' 
```
android {
    compileSdkVersion 27

    defaultConfig {
        minSdkVersion 19
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    lintOptions {
        disable 'InvalidPackage'
    }

    dependencies {
        implementation 'org.tensorflow:tensorflow-lite:+'
    }
}
```
After removing these errors. My applications crashes on startup with above error:

```
2019-05-28 14:22:45.663 28605-28605/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2019-05-28 14:22:45.665 28605-28605/? E/Zygote: accessInfo : 1
2019-05-28 14:22:45.673 28605-28605/? I/r.tfliteexampl: Late-enabling -Xcheck:jni
2019-05-28 14:22:45.819 28605-28605/sq.flutter.tfliteexample I/r.tfliteexampl: The ClassLoaderContext is a special shared library.
2019-05-28 14:22:45.962 28605-28605/sq.flutter.tfliteexample W/r.tfliteexampl: JIT profile information will not be recorded: profile file does not exits.
2019-05-28 14:22:45.967 28605-28605/sq.flutter.tfliteexample I/chatty: uid=10585(sq.flutter.tfliteexample) identical 10 lines
2019-05-28 14:22:45.968 28605-28605/sq.flutter.tfliteexample W/r.tfliteexampl: JIT profile information will not be recorded: profile file does not exits.
2019-05-28 14:22:46.012 28605-28605/sq.flutter.tfliteexample I/InstantRun: starting instant run server: is main process
2019-05-28 14:22:46.053 28605-28636/sq.flutter.tfliteexample I/ResourceExtractor: Found extracted resources res_timestamp-1-1559033195122
2019-05-28 14:22:46.075 28605-28605/sq.flutter.tfliteexample D/AndroidRuntime: Shutting down VM
2019-05-28 14:22:46.081 28605-28605/sq.flutter.tfliteexample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: sq.flutter.tfliteexample, PID: 28605
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/base.apk", zip file "/data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/split_lib_dependencies_apk.apk", zip file "/data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/split_lib_resources_apk.apk", zip file "/data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/split_lib_slice_0_apk.apk", zip file "/data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/split_lib_slice_1_apk.apk", zip file "/data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/split_lib_slice_2_apk.apk", zip file "/data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/split_lib_slice_3_apk.apk", zip file "/data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/split_lib_slice_4_apk.apk", zip file "/data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/split_lib_slice_5_apk.apk", zip file "/data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/split_lib_slice_6_apk.apk", zip file "/data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/split_lib_slice_7_apk.apk", zip file "/data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/split_lib_slice_8_apk.apk", zip file "/data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/lib/arm, /data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/base.apk!/lib/armeabi-v7a, /data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/split_lib_resources_apk.apk!/lib/armeabi-v7a, /data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/sq.flutter.tfliteexample-dj60Xz-J1vYGulJyZ9UOig==/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:161)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:136)
        at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1158)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6248)
        at android.app.ActivityThread.access$1200(ActivityThread.java:240)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1797)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7076)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by shaqian** [comment]
see https://github.com/shaqian/flutter_realtime_detection/issues/5#issuecomment-496449214

**Comment by shaqian** [comment]
Temporarily archiving the thread. Feel free to reopen if you still have the issue.
