### ISSUE TITLE
Error loading custom model

### ISSUE THREAD

**Issue by brunojus** [shaqian/flutter_tflite#62]
Hi, 

I've tried to load a custom model, but I received this error. 

```
E/filemap ( 5882): mmap(12197888,537254094) failed: Out of memory
E/.example.camer( 5882): Failed to mmap file 'assets/flutter_assets/assets/output.tflite' in APK '/data/app/com.example.camera-WawBUeaUmkWJO_ihqe9sPw==/base.apk'
E/MethodChannel#tflite( 5882): Failed to handle method call
E/MethodChannel#tflite( 5882): java.lang.IllegalArgumentException: Unsupported value: java.io.FileNotFoundException: flutter_assets/assets/output.tflite
E/MethodChannel#tflite( 5882):  at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:294)
E/MethodChannel#tflite( 5882):  at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:70)
E/MethodChannel#tflite( 5882):  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:230)
E/MethodChannel#tflite( 5882):  at sq.flutter.tflite.TflitePlugin.onMethodCall(TflitePlugin.java:95)
E/MethodChannel#tflite( 5882):  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#tflite( 5882):  at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#tflite( 5882):  at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#tflite( 5882):  at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#tflite( 5882):  at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#tflite( 5882):  at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#tflite( 5882):  at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#tflite( 5882):  at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#tflite( 5882):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#tflite( 5882):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter ( 5882): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Unsupported value: java.io.FileNotFoundException: flutter_assets/assets/output.tflite, null)
E/flutter ( 5882): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 5882): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter ( 5882): <asynchronous suspension>
E/flutter ( 5882): #2      Tflite.loadModel (package:tflite/tflite.dart:15:27)
E/flutter ( 5882): <asynchronous suspension>
E/flutter ( 5882): #3      _CameraState.loadModel (package:camera/camera.dart:27:24)
E/flutter ( 5882): <asynchronous suspension>
E/flutter ( 5882): #4      _CameraState._showChoiceDialog.<anonymous closure>.<anonymous closure> (package:camera/camera.dart:61:19)
E/flutter ( 5882): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 5882): #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter ( 5882): #7      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
E/flutter ( 5882): #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
E/flutter ( 5882): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
E/flutter ( 5882): #10     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
E/flutter ( 5882): #11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter ( 5882): #12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 5882): #13     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 5882): #14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 5882): #15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 5882): #16     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter ( 5882): #17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 5882): #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 5882): #19     _invoke1 (dart:ui/hooks.dart:263:10)
E/flutter ( 5882): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
```

**Comment by shaqian** [comment]
The error is FileNotFoundException.

Can you please check if the path "assets/output.tflite" is correct? Have you edited "pubspec.yaml"? 
https://github.com/shaqian/flutter_tflite#usage

Thanks,
Qian

**Comment by shaqian** [comment]
I'm closing the issue for now. Feel free to reopen if you have other questions.

Thanks,
Qian
