### ISSUE TITLE
Custom Model Error

### ISSUE THREAD

**Issue by bgparkloop** [shaqian/flutter_tflite#69]
Hi. I try to learn own my model and run it.

but, I get the error below. Why does it happen "out of bounds error"?

custom model have 2 classes and i set to parameters in my codes

please let me know it. so confused..

D/AndroidRuntime(31464): Shutting down VM
E/AndroidRuntime(31464): FATAL EXCEPTION: main
E/AndroidRuntime(31464): Process: doai.dopap, PID: 31464
E/AndroidRuntime(31464): java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 2
E/AndroidRuntime(31464): 	at java.util.Vector.get(Vector.java:748)
E/AndroidRuntime(31464): 	at sq.flutter.tflite.TflitePlugin$RunSSDMobileNet.onRunTfliteDone(TflitePlugin.java:634)
E/AndroidRuntime(31464): 	at sq.flutter.tflite.TflitePlugin$TfliteTask.onPostExecute(TflitePlugin.java:425)
E/AndroidRuntime(31464): 	at sq.flutter.tflite.TflitePlugin$TfliteTask.onPostExecute(TflitePlugin.java:393)
E/AndroidRuntime(31464): 	at android.os.AsyncTask.finish(AsyncTask.java:695)
E/AndroidRuntime(31464): 	at android.os.AsyncTask.access$600(AsyncTask.java:180)
E/AndroidRuntime(31464): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
E/AndroidRuntime(31464): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(31464): 	at android.os.Looper.loop(Looper.java:205)
E/AndroidRuntime(31464): 	at android.app.ActivityThread.main(ActivityThread.java:6991)
E/AndroidRuntime(31464): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31464): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(31464): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
I/Process (31464): Sending signal. PID: 31464 SIG: 9

**Comment by shaqian** [comment]
Hello,

The exception is thrown at the following line. 
https://github.com/shaqian/flutter_tflite/blob/52b242eda2992b2858f0dba09be0c0529427031c/android/src/main/java/sq/flutter/tflite/TflitePlugin.java#L634

You can set a breakpoint here. I think the int value passed to `labels.get()` is out of boundary.

Thanks,
Qian

**Comment by bgparkloop** [comment]
Thanks i correct it.
this issue is label text file has only 2 line(normal, abnormal) because i learned my model having 2 classes
I tried to add one meaningless line at first so, it run normally
I think "+1" is problem in labels.get line

**Comment by Fethi1** [comment]
how do you guys deal with image pre-processing and passing it to the model, i made a model and it is successfully loaded but it need to be on bytelist to pass to the model, while runmodelonimage function takes an image path, i wonder how can you deal with preprocessing and converting to bytelist?

**Comment by Ehtasha** [comment]
Hello @Fethi1 
Did you try this ?

Our app is crash when we send an image to the model ? 

And yes I'm sending image path. How I use bytelist ?

**Comment by shaqian** [comment]
Hi @Fethi1 @Ehtasha,

To pass bytelist to the model, you can use runModelOnBinary(). Refer to the sample code in readme for how to convert image to bytelist. 
https://github.com/shaqian/flutter_tflite#Image-Classification

Thanks,
Qian

**Comment by Fethi1** [comment]
thanks @shaqian i have solved the problem the same way

**Comment by mgalgs** [comment]
> You can set a breakpoint here. I think the int value passed to `labels.get()` is out of boundary.

@shaqian I'm trying to debug a similar issue but I'm not sure how to set a breakpoint in the plugin's java code. I've tried just clicking on the relevant line in Android Studio but that doesn't seem to have any effect. I've added a local checkout of `flutter_tflite` as a dependency in my `pubspec.yaml` which has allowed me to make changes in the plugin, I just can't set a breakpoint. Any tips?
