### ISSUE TITLE
runModelOnBinary error: Null outputs are allowed only if the Tensor is bound to a buffer handle

### ISSUE THREAD

**Issue by pbnsilva** [shaqian/flutter_tflite#72]
Hello,

I am running a slightly modified version of the `flutter_realtime_detection` example where, on button click, I call `runModelOnBinary` using a custom model.

I've tested the model on tflite for python, and it works as expected. However, I get this on my flutter project:

```bash
Caused by: java.lang.IllegalArgumentException: Null outputs are allowed only if the Tensor is bound to a buffer handle.
E/AndroidRuntime(11499): 	at org.tensorflow.lite.Tensor.copyTo(Tensor.java:147)
E/AndroidRuntime(11499): 	at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:183)
E/AndroidRuntime(11499): 	at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:275)
E/AndroidRuntime(11499): 	at org.tensorflow.lite.Interpreter.run(Interpreter.java:249)
E/AndroidRuntime(11499): 	at sq.flutter.tflite.TflitePlugin$RunModelOnBinary.runTflite(TflitePlugin.java:478)
E/AndroidRuntime(11499): 	at sq.flutter.tflite.TflitePlugin$TfliteTask.doInBackground(TflitePlugin.java:419)
E/AndroidRuntime(11499): 	at sq.flutter.tflite.TflitePlugin$TfliteTask.doInBackground(TflitePlugin.java:393)
E/AndroidRuntime(11499): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
E/AndroidRuntime(11499): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(11499): 	... 4 more
```

How can I debug this?

**Comment by shaqian** [comment]
Hi @pbnsilva,

This library doesn't support custom model at the moment. runModelOnBinary() is for image classification models with output similar to mobilenet. 

You will need to modify the tfilite.run() to accommodate the output tensor of your model. 
https://github.com/shaqian/flutter_tflite/blob/master/android/src/main/java/sq/flutter/tflite/TflitePlugin.java#L477-L479

You can refer to the implementation of RunSSDMobileNet() as an example.  
https://github.com/shaqian/flutter_tflite/blob/master/android/src/main/java/sq/flutter/tflite/TflitePlugin.java#L603-L623

Thanks,
Qian

**Comment by piyushchauhan** [comment]
@shaqian Any update on this?
