### ISSUE TITLE
Cannot copy between a TensorFlowLite tensor with shape [1, 1001] and a Java object with shape [1, 5208].

### ISSUE THREAD

**Issue by istefano82** [shaqian/flutter_tflite#75]
Hi,

I am trying to use the plugin on an androidx enabled flutter app but I am getting an error as described in the title. I have tried to even use reduced set of the TFLite plugin example app but it gives me the same error, while the original is working.
Can you help?
Link to my repo: https://github.com/istefano82/flutter_ml_image_flip 
commit sha: 47eb2f134d98923170042e28dcee76124449cc40

Launching lib/main.dart on Android SDK built for x86 in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Built build/app/outputs/apk/debug/app-debug.apk.
I/Choreographer(14534): Skipped 31 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation(14534): eglMakeCurrent: 0x92579000: ver 2 0 (tinfo 0x8f6fe7b0)
I/tflite  (14534): Initialized TensorFlow Lite runtime.
D/EGL_emulation(14534): eglMakeCurrent: 0xa45853c0: ver 2 0 (tinfo 0xa4583600)
D/EGL_emulation(14534): eglMakeCurrent: 0x92579000: ver 2 0 (tinfo 0x8f6fe7b0)
I/ExifInterface_JNI(14534): Raw image not detected
I/ExifInterface_JNI(14534): Raw image not detected
D/EGL_emulation(14534): eglCreateContext: 0xa45857e0: maj 2 min 0 rcv 2
D/EGL_emulation(14534): eglMakeCurrent: 0xa45857e0: ver 2 0 (tinfo 0xa4583600)
D/EGL_emulation(14534): eglMakeCurrent: 0x92579000: ver 2 0 (tinfo 0x8f6fe7b0)
D/EGL_emulation(14534): eglMakeCurrent: 0xa45857e0: ver 2 0 (tinfo 0xa4583600)
E/AndroidRuntime(14534): FATAL EXCEPTION: AsyncTask #2
E/AndroidRuntime(14534): Process: com.example.fluter_image_flip, PID: 14534
E/AndroidRuntime(14534): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(14534): 	at android.os.AsyncTask$3.done(AsyncTask.java:325)
E/AndroidRuntime(14534): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
E/AndroidRuntime(14534): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
E/AndroidRuntime(14534): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(14534): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
E/AndroidRuntime(14534): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/AndroidRuntime(14534): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/AndroidRuntime(14534): 	at java.lang.Thread.run(Thread.java:761)
E/AndroidRuntime(14534): Caused by: java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 1001] and a Java object with shape [1, 5208].
E/AndroidRuntime(14534): 	at org.tensorflow.lite.Tensor.throwIfShapeIsIncompatible(Tensor.java:291)
E/AndroidRuntime(14534): 	at org.tensorflow.lite.Tensor.throwIfDataIsIncompatible(Tensor.java:258)
E/AndroidRuntime(14534): 	at org.tensorflow.lite.Tensor.copyTo(Tensor.java:150)
E/AndroidRuntime(14534): 	at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:183)
E/AndroidRuntime(14534): 	at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:275)
E/AndroidRuntime(14534): 	at org.tensorflow.lite.Interpreter.run(Interpreter.java:249)
E/AndroidRuntime(14534): 	at sq.flutter.tflite.TflitePlugin$RunModelOnImage.runTflite(TflitePlugin.java:452)
E/AndroidRuntime(14534): 	at sq.flutter.tflite.TflitePlugin$TfliteTask.doInBackground(TflitePlugin.java:419)
E/AndroidRuntime(14534): 	at sq.flutter.tflite.TflitePlugin$TfliteTask.doInBackground(TflitePlugin.java:393)
E/AndroidRuntime(14534): 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
E/AndroidRuntime(14534): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(14534): 	... 4 more
I/Process (14534): Sending signal. PID: 14534 SIG: 9
Lost connection to device.
Exited (sigterm)

**Comment by istefano82** [comment]
Somehow i changed the model files inside the assets directory with ones from another app of yours - flutter_realtime_detection and they started to work. Initially I had the example app models taken from this repo and I do not know why it was failing with such error.

You can close the issue.
