### ISSUE TITLE
Buffer Error

### ISSUE THREAD

**Issue by rahulmoorthy19** [shaqian/flutter_tflite#83]
I was using the tflite  plugin of Flutter for loading a custom model for classification. While running- 
recognitions = await Tflite.runModelOnImage(
          path: widget.imagePath,
          imageMean: 127.5,
          imageStd: 127.5,
          numResults: 2,
          threshold: 0.1,
          asynch: true);
 I recieved this error-
E/AndroidRuntime(16412): Caused by: java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite buffer with 21600 bytes and a Java Buffer with 43200 bytes.
E/AndroidRuntime(16412): 	at org.tensorflow.lite.Tensor.throwIfShapeIsIncompatible(Tensor.java:332)
E/AndroidRuntime(16412): 	at org.tensorflow.lite.Tensor.throwIfDataIsIncompatible(Tensor.java:305)
E/AndroidRuntime(16412): 	at org.tensorflow.lite.Tensor.setTo(Tensor.java:123)
E/AndroidRuntime(16412): 	at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:150)
E/AndroidRuntime(16412): 	at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:311)
E/AndroidRuntime(16412): 	at org.tensorflow.lite.Interpreter.run(Interpreter.java:272)
E/AndroidRuntime(16412): 	at sq.flutter.tflite.TflitePlugin$RunModelOnImage.runTflite(TflitePlugin.java:452)
E/AndroidRuntime(16412): 	at sq.flutter.tflite.TflitePlugin$TfliteTask.doInBackground(TflitePlugin.java:419)
E/AndroidRuntime(16412): 	at sq.flutter.tflite.TflitePlugin$TfliteTask.doInBackground(TflitePlugin.java:393)
E/AndroidRuntime(16412): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
E/AndroidRuntime(16412): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

How can this be solved?

**Comment by Ehtasha** [comment]
@rahulmoorthy19  Did you resolve this problem ?

I'm also facing this problem with custom model.

**Comment by rahulmoorthy19** [comment]
Well I could not resolve it but from what I have researched this can be solved by putting the default byte size as 4(size occupied by float64) and then publishing the plugin again

changing this to 4
int bytePerChannel = 4

**Comment by Ehtasha** [comment]
@rahulmoorthy19  Thanks I have resolved this issue by changing bytePerchannel = 4.

But there is still a minor issue Model is working fine when I send image which is placed in assets folder but when I upload the image an Exception occured: Unable to load assets

`var imageBytes = (await rootBundle.load(image.path)).buffer.`

Error Statement:
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Unable to load asset: /storage/emulated/0/DCIM/Screenshots/32-128x128.png

**Comment by rahulmoorthy19** [comment]
well this is something which I cannot resolve just by looking at the error, need to see the whole code to trace back to the source of error

**Comment by Ehtasha** [comment]
Bellow is the function whaich has some problem.
 
`Future recognizeImageBinary(File image) async {

    int colorred = 0xFFeb4034;
    int colorBlack = 0xFF594e4e;
    int colorPink = 0xFF1ad9a0;
    int colorBlue = 0xFF2218db;

    // Bellow Statement works
    //var imageBytes = (await rootBundle.load('assets/32-128x128.png')).buffer;

    // image.path contain /storage/emulated/0/DCIM/Screenshots/32-128x128.png
    //  Bellow statement through exception
    var imageBytes = (await rootBundle.load(image.path)).buffer;

    final img.Image oriImage = img.decodePng(imageBytes.asUint8List());
    print('img.Image oriImage value $oriImage');


    img.Image resizedImage = img.copyResize(oriImage, width: 128, height: 128);
    print('resizedImage $resizedImage');

    var recognitions = await Tflite.runSegmentationOnBinary(
      binary: imageToByteListUint8(resizedImage, 128),
      labelColors: [colorred,colorBlack,colorPink,colorBlue],
      outputType: "png",
    );

    setState(() {
      _recognitions = recognitions;
    });
  }`

I have also try this with function `rootBundle.loadString ` function but no luck


Error Statement:
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Unable to load asset: /storage/emulated/0/DCIM/Screenshots/32-128x128.png
