### ISSUE TITLE
Crush when l load model from teachablemachine (Android)

### ISSUE THREAD

**Issue by Lykeosovandara** [shaqian/flutter_tflite#84]
On ios, everything seems fine but on **android** keeps crush whenever I load model.

**Comment by Maadhav** [comment]
Are you getting any error on the terminal?

**Comment by alectogeek** [comment]
Same here.

```
I/tflite  ( 5150): Initialized TensorFlow Lite runtime.
E/AndroidRuntime( 5150): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime( 5150): Process: com.english.language, PID: 5150
E/AndroidRuntime( 5150): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime( 5150): 	at android.os.AsyncTask$3.done(AsyncTask.java:325)
E/AndroidRuntime( 5150): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
E/AndroidRuntime( 5150): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
E/AndroidRuntime( 5150): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime( 5150): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
E/AndroidRuntime( 5150): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/AndroidRuntime( 5150): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/AndroidRuntime( 5150): 	at java.lang.Thread.run(Thread.java:761)
E/AndroidRuntime( 5150): Caused by: java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 26] and a Java object with shape [1, 27].
E/AndroidRuntime( 5150): 	at org.tensorflow.lite.Tensor.throwIfShapeIsIncompatible(Tensor.java:342)
E/AndroidRuntime( 5150): 	at org.tensorflow.lite.Tensor.throwIfDataIsIncompatible(Tensor.java:305)
E/AndroidRuntime( 5150): 	at org.tensorflow.lite.Tensor.copyTo(Tensor.java:183)
E/AndroidRuntime( 5150): 	at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:166)
E/AndroidRuntime( 5150): 	at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:311)
E/AndroidRuntime( 5150): 	at org.tensorflow.lite.Interpreter.run(Interpreter.java:272)
E/AndroidRuntime( 5150): 	at sq.flutter.tflite.TflitePlugin$RunModelOnBinary.runTflite(TflitePlugin.java:478)
E/AndroidRuntime( 5150): 	at sq.flutter.tflite.TflitePlugin$TfliteTask.doInBackground(TflitePlugin.java:419)
E/AndroidRuntime( 5150): 	at sq.flutter.tflite.TflitePlugin$TfliteTask.doInBackground(TflitePlugin.java:393)
E/AndroidRuntime( 5150): 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
E/AndroidRuntime( 5150): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime( 5150): 	... 4 more
```

**Comment by Maadhav** [comment]
Does removing one label solve the problem?
```And In android/app/build.gradle, did you add the following setting in android block.
    aaptOptions {
        noCompress 'tflite'
        noCompress 'lite'
    }```

**Comment by alectogeek** [comment]
@Maadhav Yes, removing 1 label solved problem. Though on iOS it worked well even with an excess label.
Regarding android settings: yes, I added that from the beginning.
