### ISSUE TITLE
Custom model based on PoseNet crashes when camera starts

### ISSUE THREAD

**Issue by lockr7** [shaqian/flutter_tflite#94]
Hi, I'm attempting to use model.tflite found [here ](https://github.com/smellslikeml/ActionAI/tree/master/examples/yogai/models) with tflite. However, I get this error and the app crashes when I click on the button to start the camera and load the model.

`W/Settings(25088): Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
V/HiTouch_HiTouchSensor(25088): User setup is finished.
V/AudioManager(25088): querySoundEffectsEnabled...
I/tflite  (25088): Initialized TensorFlow Lite runtime.
I/flutter (25088): success
D/SensorManager(25088): 0x7e8d72bb10 addFd fd=127
D/HwFrameworkSecurityPartsFactory(25088): HwFrameworkSecurityPartsFactory in.
I/HwFrameworkSecurityPartsFactory(25088): add HwFrameworkSecurityPartsFactory to memory.
I/CameraManager(25088): open camera: 0, package name: com.example.examplerealtime
I/HwCameraUtil(25088): notifySurfaceFlingerCameraStatus : isFront = false , isOpend = true
W/Gralloc3(25088): allocator 3.x is not supported
I/Choreographer(25088): Skipped 33 frames!  The application may be doing too much work on its main thread.
I/CameraDevice-JV-0(25088): Camera now idle
E/ion     (25088): ioctl c0044901 failed with code -1: Not a typewriter
I/GRALLOC (25088): LockFlexLayout: baseFormat: 11, yStride: 1280, ySize: 921600, uOffset: 921600,  uStride: 1280
I/GRALLOC (25088): LockFlexLayout: baseFormat: 11, yStride: 1280, ySize: 921600, uOffset: 921600,  uStride: 1280
D/RenderScript HIDL Adaptation(25088): IRenderScriptDevice::getService()
D/RenderScript HIDL Adaptation(25088): IRenderScriptDevice::getService() returned 0x7e740efbc0
D/RenderScript HIDL Adaptation(25088): HIDL successfully loaded.
V/RenderScript(25088): ARM mali (64 bit) RenderScript Compute Driver
W/System  (25088): A resource failed to call close. 
W/System  (25088): A resource failed to call release. 
V/RenderScript(25088): Successfully loaded runtime: libRSDriverArm.so
D/        (25088): Successfully queried cache dir: /data/user_de/0/com.example.examplerealtime/code_cache
D/RenderScript(25088): Setting cache dir: /data/user_de/0/com.example.examplerealtime/code_cache
D/HwGalleryCacheManagerImpl(25088): mIsEffect:false
I/GRALLOC (25088): LockFlexLayout: baseFormat: 11, yStride: 1280, ySize: 921600, uOffset: 921600,  uStride: 1280
W/System  (25088): A resource failed to call destroy. 
I/chatty  (25088): uid=10240(com.example.examplerealtime) FinalizerDaemon identical 1 line
W/System  (25088): A resource failed to call destroy. 
I/GRALLOC (25088): LockFlexLayout: baseFormat: 11, yStride: 1280, ySize: 921600, uOffset: 921600,  uStride: 1280
I/QarthLog(25088): [PatchStore] createDisableExceptionQarthFile
I/QarthLog(25088): [PatchStore] create disable file for com.example.examplerealtime uid is 10240
E/AndroidRuntime(25088): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(25088): Process: com.example.examplerealtime, PID: 25088
E/AndroidRuntime(25088): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(25088): 	at android.os.AsyncTask$4.done(AsyncTask.java:399)
E/AndroidRuntime(25088): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(25088): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(25088): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(25088): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
E/AndroidRuntime(25088): 	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
E/AndroidRuntime(25088): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
E/AndroidRuntime(25088): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(25088): 	at java.lang.Thread.run(Thread.java:929)
E/AndroidRuntime(25088): Caused by: java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 96, 96, 14] and a Java object with shape [1, 3].
E/AndroidRuntime(25088): 	at org.tensorflow.lite.Tensor.throwIfShapeIsIncompatible(Tensor.java:342)
E/AndroidRuntime(25088): 	at org.tensorflow.lite.Tensor.throwIfDataIsIncompatible(Tensor.java:305)
E/AndroidRuntime(25088): 	at org.tensorflow.lite.Tensor.copyTo(Tensor.java:183)
E/AndroidRuntime(25088): 	at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:166)
E/AndroidRuntime(25088): 	at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:311)
E/AndroidRuntime(25088): 	at org.tensorflow.lite.Interpreter.run(Interpreter.java:272)
E/AndroidRuntime(25088): 	at sq.flutter.tflite.TflitePlugin$RunModelOnFrame.runTflite(TflitePlugin.java:513)
E/AndroidRuntime(25088): 	at sq.flutter.tflite.TflitePlugin$TfliteTask.doInBackground(TflitePlugin.java:419)
E/AndroidRuntime(25088): 	at sq.flutter.tflite.TflitePlugin$TfliteTask.doInBackground(TflitePlugin.java:393)
E/AndroidRuntime(25088): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
E/AndroidRuntime(25088): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(25088): 	... 5 more
I/GRALLOC (25088): LockFlexLayout: baseFormat: 11, yStride: 1280, ySize: 921600, uOffset: 921600,  uStride: 1280
I/GRALLOC (25088): LockFlexLayout: baseFormat: 11, yStride: 1280, ySize: 921600, uOffset: 921600,  uStride: 1280
I/GRALLOC (25088): LockFlexLayout: baseFormat: 11, yStride: 1280, ySize: 921600, uOffset: 921600,  uStride: 1280
I/Process (25088): Sending signal. PID: 25088 SIG: 9`

Any help appreciated. I feel like the important error is `Caused by: java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 96, 96, 14] and a Java object with shape [1, 3].` but I could be wrong. I am willing to upload the code to a repo if that helps but I have changed very little, just cleaned the example code to remove unneeded models and switched to custom model.

**Comment by lockr7** [comment]
When loading the model I was originally using 
```
res = await Tflite.loadModel(
          model: "assets/pose.tflite",
          labels:"assets/pose.txt",
      );
```
with `pose.txt` contatining 
```
stand
squat
deadlift
```
I stopped setting `labels` and the error is now 
```
V/AudioManager(30394): querySoundEffectsEnabled...
I/tflite  (30394): Initialized TensorFlow Lite runtime.
I/flutter (30394): success
D/SensorManager(30394): 0x7e8d59dca0 addFd fd=129
D/HwFrameworkSecurityPartsFactory(30394): HwFrameworkSecurityPartsFactory in.
I/HwFrameworkSecurityPartsFactory(30394): add HwFrameworkSecurityPartsFactory to memory.
I/CameraManager(30394): open camera: 0, package name: com.example.examplerealtime
I/HwCameraUtil(30394): notifySurfaceFlingerCameraStatus : isFront = false , isOpend = true
W/Gralloc3(30394): allocator 3.x is not supported
I/CameraDevice-JV-0(30394): Camera now idle
E/ion     (30394): ioctl c0044901 failed with code -1: Not a typewriter
I/GRALLOC (30394): LockFlexLayout: baseFormat: 11, yStride: 1280, ySize: 921600, uOffset: 921600,  uStride: 1280
I/GRALLOC (30394): LockFlexLayout: baseFormat: 11, yStride: 1280, ySize: 921600, uOffset: 921600,  uStride: 1280
D/RenderScript HIDL Adaptation(30394): IRenderScriptDevice::getService()
D/RenderScript HIDL Adaptation(30394): IRenderScriptDevice::getService() returned 0x7f15550460
D/RenderScript HIDL Adaptation(30394): HIDL successfully loaded.
V/RenderScript(30394): ARM mali (64 bit) RenderScript Compute Driver
W/System  (30394): A resource failed to call close. 
W/System  (30394): A resource failed to call release. 
V/RenderScript(30394): Successfully loaded runtime: libRSDriverArm.so
D/        (30394): Successfully queried cache dir: /data/user_de/0/com.example.examplerealtime/code_cache
D/RenderScript(30394): Setting cache dir: /data/user_de/0/com.example.examplerealtime/code_cache
D/HwGalleryCacheManagerImpl(30394): mIsEffect:false
I/GRALLOC (30394): LockFlexLayout: baseFormat: 11, yStride: 1280, ySize: 921600, uOffset: 921600,  uStride: 1280
W/System  (30394): A resource failed to call destroy. 
I/chatty  (30394): uid=10240(com.example.examplerealtime) FinalizerDaemon identical 1 line
W/System  (30394): A resource failed to call destroy. 
I/GRALLOC (30394): LockFlexLayout: baseFormat: 11, yStride: 1280, ySize: 921600, uOffset: 921600,  uStride: 1280
I/QarthLog(30394): [PatchStore] createDisableExceptionQarthFile
I/QarthLog(30394): [PatchStore] create disable file for com.example.examplerealtime uid is 10240
E/AndroidRuntime(30394): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(30394): Process: com.example.examplerealtime, PID: 30394
E/AndroidRuntime(30394): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(30394): 	at android.os.AsyncTask$4.done(AsyncTask.java:399)
E/AndroidRuntime(30394): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(30394): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(30394): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(30394): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
E/AndroidRuntime(30394): 	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
E/AndroidRuntime(30394): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
E/AndroidRuntime(30394): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(30394): 	at java.lang.Thread.run(Thread.java:929)
E/AndroidRuntime(30394): Caused by: java.lang.IllegalArgumentException: Null outputs are allowed only if the Tensor is bound to a buffer handle.
E/AndroidRuntime(30394): 	at org.tensorflow.lite.Tensor.copyTo(Tensor.java:180)
E/AndroidRuntime(30394): 	at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:166)
E/AndroidRuntime(30394): 	at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:311)
E/AndroidRuntime(30394): 	at org.tensorflow.lite.Interpreter.run(Interpreter.java:272)
E/AndroidRuntime(30394): 	at sq.flutter.tflite.TflitePlugin$RunModelOnFrame.runTflite(TflitePlugin.java:513)
E/AndroidRuntime(30394): 	at sq.flutter.tflite.TflitePlugin$TfliteTask.doInBackground(TflitePlugin.java:419)
E/AndroidRuntime(30394): 	at sq.flutter.tflite.TflitePlugin$TfliteTask.doInBackground(TflitePlugin.java:393)
E/AndroidRuntime(30394): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
E/AndroidRuntime(30394): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(30394): 	... 5 more
I/examplerealtim(30394): Waiting for a blocking GC ProfileSaver
I/GRALLOC (30394): LockFlexLayout: baseFormat: 11, yStride: 1280, ySize: 921600, uOffset: 921600,  uStride: 1280
I/GRALLOC (30394): LockFlexLayout: baseFormat: 11, yStride: 1280, ySize: 921600, uOffset: 921600,  uStride: 1280
W/libEGL  (30394): EGLNativeWindowType 0x7e958e2010 disconnect failed
I/Process (30394): Sending signal. PID: 30394 SIG: 9
Lost connection to device.
```

**Comment by ab-dev-github** [comment]
Are you successful in using this? I am facing similar issue and do not have any solution.

**Comment by lockr7** [comment]
I was not but maybe look into this package https://pub.dev/packages/tflite_flutter

**Comment by Biunoctium** [comment]
Why would you stop using labels ? Without labels, how can the model give you results ?
(maybe I didn't understand the role of labels, I just started using tensorflow)

**Comment by ab-dev-github** [comment]
> I was not but maybe look into this package https://pub.dev/packages/tflite_flutter

I have tried this, but the accuracy is too low for some reason, not sure if I am using it incorrectly or there's problem with the package. I also saw similar thing mentioned on Stackover/Githib if I am not wrong.

Any one successful in using tflite_flutter package with good accuracy for Posenet? The ml5.js version has much better accuracy. 

Thank you.

**Comment by supermarille** [comment]
> I'm facing the same issue with the tensor shapes.
> Why would you stop using labels ? Without labels, how can the model give you results ?
> (maybe I didn't understand the role of labels, I just started using tensorflow)

I managed to fix this error in my case so I comment here for anyone else in trouble.
`Cannot copy between a TensorFlowLite tensor with shape [1, 1001] and a Java object with shape [1, 3].
`
it was due to a wrong label files. The label files should look something like this https://github.com/shaqian/flutter_tflite/blob/master/example/assets/mobilenet_v1_1.0_224.txt

**Comment by lockr7** [comment]
> > I'm facing the same issue with the tensor shapes.
> > Why would you stop using labels ? Without labels, how can the model give you results ?
> > (maybe I didn't understand the role of labels, I just started using tensorflow)
> 
> I managed to fix this error in my case so I comment here for anyone else in trouble.
> `Cannot copy between a TensorFlowLite tensor with shape [1, 1001] and a Java object with shape [1, 3]. `
> it was due to a wrong label files. The label files should look something like this https://github.com/shaqian/flutter_tflite/blob/master/example/assets/mobilenet_v1_1.0_224.txt

Yeah I found that fix but unfortunately it's not the solution to this issue because the TensorFlowLite tensor with shape [1, 96, 96, 14] has a length of 4 and the Java object (the second number represents the length of the label files so 3 in this case) with shape [1, 3] is only length 2. I'm not sure what else needs to change to get the Java object to be a 4 length array.
